services:
  backend: 
    image: "samuelnnechefu/ueyes-backend"
    volumes:
      - ./db/ueyes_service_account_key.json:/app/db/ueyes_service_account_key.json:ro
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    develop:
      watch:
        - action: sync 
          path: .
          target: /app
          ignore: 
            - .venv/
        - action: rebuild
          path: ./pyproject.toml


